color WHITE

drive_forward_gyro(distance=980 speed=100)
turn_left_on_spot(angle=52 speed=20)
drive_forward_gyro(distance=1000 speed=80)

drive_forward_time_gyro(time=600 speed=10)

wait_global_timer(index=0 time=146700)

// Solve Uboot
module_right_cw(distance=650 speed=100)
module_left_ccw(distance=130 speed=80)

wait_ms(time=1000)

tasksplit {
    module_left_cw(distance=130 speed=80)
}

// Wait to match end
drive_backward_gyro(distance=150 speed=40)
